### PR TITLE
Update README, add jumpserver project

### PR DESCRIPTION
**Pull request by ibuler**
## JumpServer

**1Password Teams url**: https://jumpserver.1password.com/

**Project name**:  JumpServer

**Short description**: JumpServer is a popular open-source PAM (Privileged Access Management System) 

**Project age**: 7 year

**Number of core contributors**: 10

**Project website**: https://www.jumpserver.org

**Repository url**: https://github.com/jumpserver/jumpserve

**Latest release url**: https://github.com/jumpserver/jumpserver/releases/tag/v2.6.2

**License type**:  GPLv2

**License url**: https://github.com/jumpserver/jumpserver/blob/master/LICENSE

## Tell us about yourself

**Name**: ibuler

**Email**: ibuler@qq.com

**Project role**: Manager

**Website**: https://github.com/ibuler

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi @ibuler! Thanks for your application - looks like a great project 😄 

Would you be able to explain the separation between open source and enterprise at JumpServer? Some amount of financial support is ok, but one exception to this program is for-profit companies who happen to release some of their software as open source. We're able to provide these accounts to open source contributors but not all of the employees of a business.

**Comment by ibuler** [comment]
Enterpise version include open source and xpack plugins, Plugin same with elastic Xpack

**Comment by oliverdunk** [comment]
Hi @ibuler, thanks for replying. That sounds completely fine. I sent you one quick email, because I noticed something that we need to resolve before we can get this merged. Do you mind taking a look at that?

Appreciate your patience.

**Comment by oliverdunk** [comment]
Thanks for your patience, @ibuler! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under two year's time, as explained in the README. That way, we can look at continuing our support.

**Pull request merged**
