### PR TITLE
Add onelitefeather

### PR DESCRIPTION
**Pull request by TheMeinerLP**
#### 1Password Teams URL
onelitefeather.1password.com

#### Project Name
OneLiteFeather

#### Short Description
OneLiteFeather is a Minecraft Network focusing on the development tools, plugins and more with intention to share with other servers. 

#### Project Age
06 December 2020 - almost 3 Year

#### Number Of Core Contributors
4

#### Project Website
https://github.com/OneLiteFeatherNET

#### Repository URL(s)
https://github.com/OneLiteFeatherNET/Microtus

#### Latest Release URL(s)
https://github.com/OneLiteFeatherNET/Microtus/releases/tag/1.1.1

#### License
MIT

#### Name
Phillipp Glanz

#### Email
1password@themeinerlp.dev

#### Project Role
Core and infrastructure maintainer

#### Profile/Website
https://github.com/TheMeinerLP

#### Can we contact you?
We'd love to be in touch to learn how you're using 1Password. Would you be open to our Developer Advocates reaching out?

- [X] Yes, I'm open.

### CODE REVIEW

**Comment by jodyheavener** [comment]
Hi @TheMeinerLP thanks for your application. It looks like the email you listed is not an account owner. Would you be able to list an account owner email for verification?

**Comment by TheMeinerLP** [comment]
> Hi @TheMeinerLP thanks for your application. It looks like the email you listed is not an account owner. Would you be able to list an account owner email for verification?

I updated the email. I associated both to my account.

**Comment by TheMeinerLP** [comment]
> Hi @TheMeinerLP - it looks like the new email you provided is not an owner of the account listed. Would you be able to reach out to [opensource@1password.com](mailto:opensource@1password.com) and we can continue there?

So sorry, i was thinking in this section you mean the E-Mail thats associated with Github and not 1Password its self. I corrected that and hope now everything is fine. When not i will contact you via this give e-mail.

**Comment by jodyheavener** [comment]
Awesome, thanks for updating for me, @TheMeinerLP! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would highly recommend implementing a [recovery plan for your team](https://support.1password.com/team-recovery-plan/) in case access for a particular contributor is ever lost. You are also welcome to add additional core contributors as you see fit.

Also, we'd love to hear more about your experience using 1Password in your development workflows! Feel free to join us over on the [1Password Developers Slack](https://join.slack.com/t/1password-devs/shared_invite/zt-15k6lhima-GRb5Ga~fo7mjS9xPzDaF2A) workspace 🙂

**Pull request merged**
