### PR TITLE
Clean up and update pull_request_template.md

### PR DESCRIPTION
**Pull request by blag**
This PR just cleans up and updates the PR template.

It uses GitHub-Flavored Markdown headers instead of emphasis, and converts some of the notes to HTML comments so they appear to PR authors but they won't be included in the rendered output.

### CODE REVIEW

**Comment by oliverdunk** [comment]
Thanks for this! Do you have a reference that explains the use of trailing # characters? It's not syntax I'm familiar with so I'm curious about the thinking behind it :)

**Comment by blag** [comment]
Apparently that syntax is not as well known as I thought. That was how I learned Markdown way back in the day. I guess I like it because it reminds me of HTML opening and closing tags, or perhaps it just makes headings look more balanced to me.

To me, this:

```markdown
### Subsection Heading
```

just looks like it is weighted to the left for some reason, reminding me of unbalanced HTML tags, but this:

```markdown
### Subsection Heading ###
```

looks heavy, but at least looks like the section heading "tag" `###` has a matching closing tag.

According to [gitbooks.io](https://gitbookio.gitbooks.io/markdown/content/syntax/titles.html):

> Optionally, you may “close” atx-style headers. This is purely cosmetic — you can use this if you think it looks better. The closing hashes don’t even need to match the number of hashes used to open the header. (The number of opening hashes determines the header level.)
> ```
> # This is an H1 #
> 
> ## This is an H2 ##
> 
> ### This is an H3 ######
> ```

Here's a [SO post](https://stackoverflow.com/questions/13537826/how-do-i-add-a-trailing-hash-to-a-header-in-github-flavored-markdown) where they mention that GitHub-Flavored Markdown is interpreting trailing hash marks as optional closing header tags:

> Now I want to set the text of one headline to `C#`, but GitHub does not respect the hash a part of the text, but interprets it as an (optional) closing hash for the headline.

And while it doesn't include an example of them, here is the [GitHub Flavored Markdown specification itself discussing what it calls "ATX headings"](https://github.github.com/gfm/#atx-headings) (emphasis mine):

> An ATX heading consists of a string of characters, parsed as inline content, between an opening sequence of 1–6 unescaped # characters and an **optional closing sequence of any number of unescaped # characters**. The opening sequence of # characters must be followed by a space or by the end of line. The optional closing sequence of #s must be preceded by a space and may be followed by spaces only.

I'm happy to change it to whatever looks better to you.

**Comment by oliverdunk** [comment]
Hah, thanks for all of the info! I had no idea about this, so definitely learnt something new today.

Would you be up for removing the closing symbols, or at least making them match the number of opening symbols? Post that I'm happy to merge.

**Comment by blag** [comment]
You're welcome, I'm happy to have helped out.

And shoot, I didn't even notice that that first header was unbalanced. I have balanced it now. I'm pretty sure that was the only unbalanced one, but if you notice any more I'm happy to correct them.

**Comment by oliverdunk** [comment]
Brilliant, thanks! Merging now...

**Pull request merged**
