### PR TITLE
update: add Falco

### PR DESCRIPTION
**Pull request by fntlnz**
## Your project

**1Password Teams url**: falcosecurity.1password.com (create the account before applying).

**Project name**:  Falco

**Short description**:

An Open Source Cloud-Native runtime security project that makes it easy to trigger alerts based on kernel events enriched with information from Kubernetes and the rest of the cloud native stack.

**Project age**: 4 years

**Number of core contributors**: 6

**Project website**: https://falco.org

**Repository url**: https://github.com/falcosecurity/falco

**Latest release url**: https://github.com/falcosecurity/falco/releases/tag/0.26.1

**License type**: Apache 2

**License url**: https://github.com/falcosecurity/falco/blob/master/COPYING

## Tell us about yourself

**Name**: Lorenzo Fontana	

**Email**: `lo at linux.com`

**Project role**: Maintainer

**Website**: https://github.com/fntlnz https://fntlnz.wtf

### CODE REVIEW

**Comment by oliverdunk** [comment]
Thanks for your application, @fntlnz! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under a year's time, as explained in the README. That way, we can look at continuing our support.

**Comment by fntlnz** [comment]
Thank you @oliverdunk - The team will have a meeting to decide that. Thanks for all you do!

**Comment by fntlnz** [comment]
Hi @oliverdunk I just noticed that the @falcosecurity 1password account is now in trial mode and expires in 124 days. Did something change in this program?

Thanks,
Lore

**Comment by oliverdunk** [comment]
Hi @fntlnz - we use trials as our way of providing this promotion, so all is good! Per the README, was ask that you reach out once a year (this was recently changed to two years) so we can check your eligibility and potentially extend the offer. Hope that helps!

**Pull request merged**
