### PR TITLE
Add FemiWiki

### PR DESCRIPTION
**Pull request by revi**
## Your project

**1Password Teams url**: femiwiki.1password.com (create the account before applying).

**Project name**:  FemiWiki

**Short description**: FemiWiki launched as a community effort to counter prevalent misogynistic, male-centered sources of Korean language information online that was also lacking in inclusivity towards most categories of minorities.

**Project age**: launched July 2016, 3 years and 6~7 months.

**Number of core contributors**: 21

**Project website**: https://femiwiki.com

**Repository url**: https://github.com/femiwiki (various repositories)

**Latest release url**: https://hub.docker.com/r/femiwiki/mediawiki/tags

**License type**: AGPL3.0 or later

**License url**: https://github.com/femiwiki/docker-mediawiki/blob/master/LICENSE

## Tell us about yourself

**Name**: Yongmin Hong

**Email**: revi@pobox.com

**Project role**: developer

**Website**: @revi

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi @revi! It looks like there's a conflict here, and unfortunately, I don't have access to resolve it. Could you fix it on your branch for me?

**Comment by revi** [comment]
@oliverdunk Hi, rebased!

**Comment by oliverdunk** [comment]
Thanks for doing that! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under a year's time, as explained in the README. That way, we can look at continuing our support.

**Comment by simnalamburt** [comment]
Thank you! We’ve been using GPG (😢) as password manager, and even forced it to use to people who are not programmers.(😭)

Thing became much better thanks to your kind support!

**Pull request merged**
