### PR TITLE
Laravel 5 Repositories

### PR DESCRIPTION
**Pull request by bsormagec**
#### Project Name ####
Laravel 5 Repositories

#### Short Description ####
Laravel 5 Repositories is used to abstract the data layer, making our application more flexible to maintain.

#### Project Age ####
6 Years

#### Number Of Core Contributors ####
3

#### Project Website ####
https://github.com/andersao/l5-repository

#### Repository URL(s) ####
https://github.com/andersao/l5-repository

#### Latest Release URL(s) ####
https://github.com/andersao/l5-repository/releases/tag/2.7.8

#### License Type ####
MIT

#### License URL ####
https://github.com/andersao/l5-repository/blob/master/LICENSE.md

#### Name ####
Burak Sormagec

#### Project Role ####
Lead Maintainer and Community Manager

#### Profile/Website ####
https://github.com/bsormagec

#### Comments ####
I am maintaining and managing a community that projects last 2 years.

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi @bsormagec 👋  Have you created a 1Password Teams account yet? Once you've done that, if you let me know your team URL and email, I can get this applied for you :)

**Comment by bsormagec** [comment]
> Hi @bsormagec 👋 Have you created a 1Password Teams account yet? Once you've done that, if you let me know your team URL and email, I can get this applied for you :)

I have hide it with comment it is in sourcecode @oliverdunk debiansys.1password.com

**Comment by bsormagec** [comment]
is there any update @oliverdunk

**Comment by oliverdunk** [comment]
All good @bsormagec! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under two year's time, as explained in the README. That way, we can look at continuing our support.

**Pull request merged**
