### PR TITLE
Add WePublish

### PR DESCRIPTION
**Pull request by tomaszdurka**
#### 1Password Teams URL ####
wepublish.1password.com

#### Project Name ####
We.Publish

#### Short Description ####
We.Publish is the new digital infrastructure of the Swiss media landscape where journalistic media/publishers can create and present their articles with intensive networking possibilities. As a foundation, the We.Publish Foundation promotes independent journalistic offerings and media diversity in Switzerland.

#### Project Age ####
since summer 2019

#### Number Of Core Contributors ####
6

#### Project Website ####
https://wepublish.ch/

#### Repository URL(s) ####
https://github.com/wepublish/wepublish
git@github.com:wepublish/wepublish.git

#### Latest Release URL(s) ####
https://editor.demo.wepublish.media/
https://api.demo.wepublish.media/

#### License Type ####
MIT

#### License URL ####
https://github.com/wepublish/wepublish/blob/master/LICENSE

#### Name ####
Tomasz Durka

#### Email ####
tomasz@wepublish.ch

#### Project Role ####
Dev Team Lead

#### Profile/Website ####
https://github.com/wepublish

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hey @tomaszdurka! Thanks for your application. Would you be able to share a little bit more about how you intend to use 1Password, and if it's for a small development team or the entire foundation? I'm super keen to help but am unsure if this is a better fit for 1Password Teams for Open Source or our non-profit discounts :)

**Comment by oliverdunk** [comment]
Closing this for now. If you want to reply with more information, I'd be happy to re-open and take another look.

**Comment by tomaszdurka** [comment]
Hey Oliver,

Sorry for delay. Actually our 1pass trial is getting close to an end so it would be great to finalise this (if we qualify). 

We intend to use 1password for our development team which consists of about 6 devs right now. We need 1password for sharing credentials used for our dev process - k8s clusters, db accesses, gcloud keys, dev env payment providers. We create only open-source projects gathered under https://github.com/wepublish organisation. Our main project is wepublish platform - a cms for publishers and newsrooms. Currently most of our users are from Switzerland where we are located, but platform can be used worldwide in future.

Please let me know if that fits.

Thanks,
Tomasz

**Comment by tomaszdurka** [comment]
@oliverdunk please let me know if we qualify. Thanks !

**Comment by tomaszdurka** [comment]
@oliverdunk can you please check again if we could use 1password for OS?

Many thanks,
Tomasz

**Pull request closed without merging**
