### PR TITLE
Add Cucumber to README.md

### PR DESCRIPTION
**Pull request by mattwynne**
#### 1Password Teams URL
cucumberbdd.1password.com

#### Project Name
Cucumber

#### Short Description
Automated acceptance tests, written in plain language.

#### Project Age
15 years!

#### Number Of Core Contributors
~10 regulars

#### Project Website
https://cucumber.io

#### Repository URL(s)
https://github.com/cucumber

#### Latest Release URL(s)
https://github.com/cucumber/cucumber-js/releases/tag/v10.0.1
https://github.com/cucumber/cucumber-ruby/releases/tag/v9.0.2
https://github.com/cucumber/cucumber-jvm/releases/tag/v7.14.0
https://github.com/cucumber/godog/releases

#### License
MIT
https://github.com/cucumber/cucumber-js/blob/main/LICENSE
https://github.com/cucumber/cucumber-ruby/blob/main/LICENSE
https://github.com/cucumber/cucumber-jvm/blob/main/LICENCE

#### Name
Matt Wynne 👋🏻

#### Email
matt@mattwynne.net

#### Project Role
Co-lead

#### Profile/Website
https://mattwynne.net

#### Anything else to add?
We're in a funny transitory state. You can read more context at https://mattwynne.net/new-beginning. Essentially we are migrating away from a large corporate sponsor, who currently pays for a 1Password account at http://cucumber-ltd.1password.com

#### Can we contact you?
We'd love to be in touch to learn how you're using 1Password. Would you be open to our Developer Advocates reaching out?

- [x] Yes, I'm open.

### CODE REVIEW

**Comment by jodyheavener** [comment]
Hey @mattwynne - thanks for your application (and apologies for the delay)! Love Cucumber and excited to see this application. One question before I can proceed, though - from the [Cucumber site](https://cucumber.io/) I see links to CucumberStudio, which appears to be a paid product. You mentioned transitioning away from a corporate sponsor, but I just wanted to double check that this account won't be used for commercial activity. Is that correct?

**Comment by mattwynne** [comment]
Hi @jodyheavener. Yes, the Cucumber website will be moving over to https://resplendent-hamster-2868c5.netlify.app (source https://github.com/cucumber/website) in the coming weeks. Setting up this new 1Password account for the open source maintainers is part of preparing for that transition. Please ping me matt@mattwynne.net for more details - I can't speak about all of what's going in public just yet.

**Comment by jodyheavener** [comment]
Awesome, thanks for this info, @mattwynne! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would highly recommend implementing a [recovery plan for your team](https://support.1password.com/team-recovery-plan/) in case access for a particular contributor is ever lost. You are also welcome to add additional core contributors as you see fit.

Also, we'd love to hear more about your experience using 1Password in your development workflows! Feel free to join us over on the [1Password Developers Slack](https://join.slack.com/t/1password-devs/shared_invite/zt-15k6lhima-GRb5Ga~fo7mjS9xPzDaF2A) workspace 🙂

**Comment by mattwynne** [comment]
Thanks @jodyheavener!

**Pull request merged**
