### PR TITLE
Add devonfw

### PR DESCRIPTION
**Pull request by javabean**
## Your project

**1Password Teams url**: https://devonfw.1password.eu/

**Project name**:  devonfw

**Short description**: open source software development platform

**Project age**: 6 years

**Number of core contributors**: 30

**Project website**: https://devonfw.com/

**Repository url**: https://github.com/devonfw/

**Latest release url**: https://github.com/devonfw/devon4j/releases

**License type**: Apache Licence 2.0

**License url**: https://github.com/devonfw/devon4j/blob/develop/LICENSE

## Tell us about yourself

**Name**: Cédrik LIME

**Email**: github [@at] cedrik.fr

**Project role**: core contributor

**Website**: https://github.com/javabean

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi @javabean, thanks for your application. Your project looks great! Is there somewhere where I can verify your involvement? I wasn't able to find any activity from you in the repos so I just want to double check.

**Comment by javabean** [comment]
Hi @oliverdunk 
Thank you for your kind words.
While I am part of the devonfw team, I only contribute outside of GitHub for this project (e.g. Slack, mailing lists, IRL events back when we could do in-person meetings).
You can find contributions from Jörg Hohwiller https://github.com/hohwille who asked me to take care of this application.
Shall I ask Jörg to comment this PR so that you can verify my sayings?

**Comment by hohwille** [comment]
Hi there, I am Jörg Hohwiller and one of the key players in devonfw. I mandated @javabean to do this request. Also I am working together with him on devonfw even though he was not active in the code yet.

**Comment by oliverdunk** [comment]
Thanks for jumping in @hohwille. It's nothing too formal, just a quick check to make sure that nobody is applying under your name! All looks good so I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under a year's time, as explained in the README. That way, we can look at continuing our support.

**Pull request merged**
