### PR TITLE
Add vue-notion

### PR DESCRIPTION
**Pull request by janniks**
#### 1Password Teams URL ####

vue-notion.1password.com

#### Project Name ####
vue-notion

#### Short Description ####
Build open-source tools around Notion and Vue

#### Project Age ####
10 months

#### Number Of Core Contributors ####
2

#### Project Website ####
https://vue-notion.vercel.app/

#### Repository URL(s) ####
https://github.com/janniks/vue-notion

#### Latest Release URL(s) ####
https://github.com/janniks/vue-notion/releases/tag/1.2.1

#### License Type ####
MIT

#### License URL ####
https://github.com/janniks/vue-notion/blob/main/LICENSE

## A Bit About Yourself  ##
Full-stack engineer inspired by great UX and tricky technical problems. Moonlighting on a [personal search engine side-project](https://mmry.io) — always looking for new opportunities.

#### Name ####
Jannik Siebert

#### Email ####
kidders.cutout_0g {at} icloud.com (forwards to real email, due to public forum)

#### Project Role ####
Owner/Maintainer

#### Profile/Website ####
https://janniks.com

### CODE REVIEW

**Comment by oliverdunk** [comment]
Thanks for your application, @janniks! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under two year's time, as explained in the README. That way, we can look at continuing our support.

**Comment by janniks** [comment]
Just got an email mentioning the account was frozen (/trial ended).
Is this still available? (I did change the team id a while back)

**Comment by jodyheavener** [comment]
Hey @janniks, thanks for the note here. If you can write into opensource@1password.com with a link to this PR I'd be happy to help get it sorted for you. Thanks!

**Comment by janniks** [comment]
Thanks, that worked 🙏🏻

**Pull request merged**
