### PR TITLE
Add APIs You Won't Hate

### PR DESCRIPTION
**Pull request by mbifulco**
## Your project

**1Password Teams url**: https://team-apisyouwonthate.1password.com/people

**Project name**:  APIs You Won't Hate

**Short description**: APIs You Won't Hate is dedicated to learning, writing, sharing ideas and bettering understanding of API practices. Together we can erradicate APIs we hate. Join us on the largest API chat group on the internet for help with your APIs.

**Project age**: 7 years

**Number of core contributors**: 3

**Project website**: https://apisyouwonthate.com

**Repository url**: https://github.com/apisyouwonthate/apisyouwonthate.com

**Latest release url**: https://github.com/apisyouwonthate/apisyouwonthate.com/commit/c47915acc31e45c9063e9694f07aebce0321afd6

**License type**: MIT

**License url**: https://github.com/apisyouwonthate/apisyouwonthate.com/blob/master/LICENSE

## Tell us about yourself

**Name**: Mike Bifulco

**Email**: mbifulco@live.com

**Project role**: co-owner, co-author of _Surviving Other People's APIs_, APIs You Won't Hate podcast cohost, site maintainer

**Website**: https://mike.biful.co, https://github.com/mbifulco

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi Mike,

Could you resolve the conflicts here for me? I'll then go ahead and get this merged.

**Comment by mbifulco** [comment]
All set @oliverdunk! Thank you! 🎊

**Comment by mbifulco** [comment]
Hey there, anything else I can do to help here?

**Comment by oliverdunk** [comment]
Sorry for keeping you waiting @mbifulco. I've sent an email to you, as there's one more thing that I need to check. Once that's sorted, I'll finally get this merged.

**Comment by oliverdunk** [comment]
Hi @mbifulco! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under a year's time, as explained in the README. That way, we can look at continuing our support.

**Pull request merged**
