### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TTRYMarko**
Added Tietoturva.fi

## Your Project ##

Finnish Information Security Association

#### 1Password Teams URL ####
https://team-ttry.1password.com

#### Project Name ####
Finnish Information Security Association

#### Short Description ####
Finnish Information Security Association is the largest network of information security professionals in Finland. The association's main objective is to promote cooperation in the field of information security and to act as a link between its members, as well as to promote good security practices in all areas of information security.

#### Project Age ####
25y

#### Number Of Core Contributors ####
8-10 (the board of the association)

#### Project Website ####
https://tietoturva.fi

#### Repository URL(s) ####
N/A

#### Latest Release URL(s) ####
N/A

#### License Type ####
N/A

#### License URL ####
N/A

#### Name ####
Marko Mantere

#### Email ####
marko.mantere@tietoturva.fi

#### Project Role ####
Member of the Board

#### Profile/Website ####
https://www.linkedin.com/in/markomantere/

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hey @TTRYMarko 👋  Would you be able to share some more about the organisation? This promotion is mostly for open source projects, although we do occasionally make exceptions for some non-profits and community groups. We're definitely keen to help where appropriate but any information about your charitable/non-profit status and how the group is run would be useful here :)

**Comment by oliverdunk** [comment]
Hey @TTRYMarko, just sending another bump here! If you aren't able to reply, I can close this one for now and we can always re-open if we need to.

**Comment by oliverdunk** [comment]
Closing this for now, let me know if you'd like it reopening!

**Comment by TTRYMarko** [comment]
Hi,

Sorry for the late reply but I was only now able to return to this topic.
Most of the information of our non-profit association is available in the
website https://tietoturva.fii, unfortunately in Finnish. Whatever
information you need, I will provide.

So we are a national, non-profit. association of information security
professionals and our focus groups are CISOs and ISOs of Finnish
organizations. We liken us to be the "helsec <https://helsec.fi>" for more
administrative personnel (cisos). The association is run by a 8-person
board, which is selected annually.

I translated our rules to EN (with Deepl) :
https://docs.google.com/document/d/14bm1yYEOrlGio7DJslUxe_wpWUtJofq955jQbk4lqRc/edit?usp=sharing


-Marko-



to 11. marrask. 2021 klo 12.58 Oliver Dunk ***@***.***)
kirjoitti:

**Comment by oliverdunk** [comment]
Thanks for your application, @TTRYMarko! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

**Pull request merged**
