### PR TITLE
Add SVGPT

### PR DESCRIPTION
**Pull request by vuhai16**
#### Project Name ####
SVGPT
#### Short Description ####
SVGPT is a chat configuration server using ChatGPT
#### Project Age ####
6 months
#### Number Of Core Contributors ####
2
#### Project Website ####
https://github.com/vuhai16/SVGPT

#### Repository URL(s) ####
https://github.com/vuhai16/SVGPT
#### Latest Release URL(s) ####
https://github.com/vuhai16/SVGPT/releases/tag/ChatGPT_V1.0
#### License Type ####
[MIT LICENSE](https://github.com/vuhai16/SVGPT/blob/main/LICENSE)

#### License URL ####
https://github.com/vuhai16/SVGPT/blob/main/LICENSE

#### Name ####
Vu Hai
#### Email ####
vuhai16@outlook.com
#### Project Role ####
Developer
#### Profile/Website ####
https://github.com/vuhai16

#### Comments ####
I hope project is useful for everyone

### CODE REVIEW

**Comment by jodyheavener** [comment]
Hi @vuhai16! Thanks for your application. We usually ask to see a project with at least 30 days of activity. Based on the submitted project’s commit history it looks like this might not be the case. If there is something I’m missing let me know and I will take another look, otherwise would you be up for re-applying when your project is a little older?

**Comment by vuhai16** [comment]
> Hi @vuhai16! Thanks for your application. We usually ask to see a project with at least 30 days of activity. Based on the submitted project’s commit history it looks like this might not be the case. If there is something I’m missing let me know and I will take another look, otherwise would you be up for re-applying when your project is a little older?

**Comment by vuhai16** [comment]
Actually, the project I built is on my local computer, I have only pushed it to github until now, and the project is still developing further. Hope to be able to contribute a little for everyone. Thank you

**Comment by jodyheavener** [comment]
Hey @vuhai16, thanks for this info - I love that you're wanting to write open source for everyone! For this program, however, we want to ensure that we're supporting active projects, so I'd encourage you to reach back out to us (you can even re-open this) after your project has around 30 days of public commit history, and we can get you enrolled. I appreciate your patience!

**Comment by vuhai16** [comment]
Hi @jodyheavener,
My project meets the requirements now, and I hope you can reconsider it. 

Thank you very much.

**Comment by jodyheavener** [comment]
Thanks for following up @vuhai16! I don't see a 1Password account at the URL you provided in your application. Can you clarify the URL for the 1Password account you want to apply to the program with?

**Comment by vuhai16** [comment]
Hi @jodyheavener, 

I forgot to register before, I registered a new 1password account with the URL I provided above: 
https://hideon.1password.com

Thank you so much!

**Comment by jodyheavener** [comment]
Hi @vuhai16, thanks for this info. I have sent a quick email to the owner listed in that account, once I hear back I can proceed with the application.

**Comment by vuhai16** [comment]
Hi @jodyheavener,
i'm confirmed via mail
Thanks

**Pull request merged**
