### PR TITLE
Add Kali Linux to Open Source Projects

### PR DESCRIPTION
**Pull request by g0tmi1k**
## Your project

**1Password Teams url**: https://kalilinux.1password.com/

**Project name**: Kali Linux

**Short description**: Kali Linux is a Debian-based Linux distribution aimed at advanced Penetration Testing and Security Auditing.

**Project age**: 6 years, 8 months

**Number of core contributors**: Less than 10

**Project website**: https://www.kali.org/

**Repository url**: http://gitlab.com/kalilinux/

**Latest release url**: https://www.kali.org/releases/kali-linux-2019-4-release/

**License type**: GNU General Public License v3

**License url**: https://www.kali.org/docs/policy/kali-linux-open-source-policy/

## Tell us about yourself

**Name**: g0tmi1k

**Email**: [removed because of spam worries]

**Project role**: Developer

**Website**: https://twitter.com/g0tmi1k

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi! I'm trying to verify that you're associated with the project, but I wasn't able to do that, and your email isn't listed here. Could you email opensource@1password.com for me, so we can work things out? If you have a company email, that would be best.

Look forward to hearing from you!

**Comment by g0tmi1k** [comment]
Thanks @oliverdunk. Email sent (and reply too!). Fixed merge conflict.

**Comment by oliverdunk** [comment]
Hi @g0tmi1k, I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under a year's time, as explained in the README. That way, we can look at continuing our support.

**Comment by g0tmi1k** [comment]
Hello @oliverdunk Thank you! <3

Have done and will do!

**Pull request merged**
