### PR TITLE
Add Blueprint to the projects list

### PR DESCRIPTION
**Pull request by xpyxel**
## Your project

**1Password Teams url**: https://blueprintteam.1password.com/

**Project name**: Blueprint

**Short description**: Blueprint is a fully open source bot framework based on the [eris](https://abal.moe/Eris/) Discord library. The framework is meant to make prototyping applications for the Discord chat platform faster and easier with the use of TypeScript and many other tools.

**Project age**: 3 months

**Number of core contributors**: 2

**Project website**: https://github.com/xpyxel/blueprint

**Repository url**: https://github.com/xpyxel/blueprint

**Latest release url**: https://github.com/xpyxel/blueprint/packages/527783

**License type**: Mozilla Public License 2.0

**License url**: https://github.com/xpyxel/blueprint/blob/main/LICENSE

## Tell us about yourself

**Name**: Hanna Rose

**Email**: me@pyxel.pro

**Project role**: Lead Developer and Maintainer

**Website**: https://github.com/xpyxel

### CODE REVIEW

**Comment by oliverdunk** [comment]
Thanks for your application, @xpyxel! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under a year's time, as explained in the README. That way, we can look at continuing our support.

**Comment by xpyxel** [comment]
Both me and my colleague have lost access to the team, is there any way to recover it? Neither of us have our master keys or emergency kits.

**Comment by xpyxel** [comment]
We have had support delete the old account and make a new one, but the Open Source promotion has not yet been applied to it.

**Comment by oliverdunk** [comment]
> We have had support delete the old account and make a new one, but the Open Source promotion has not yet been applied to it.

Hi! It looks like this may have been sorted for you. If not, would you be able to email opensource@1password.com from the email on the account?

**Comment by xpyxel** [comment]
It has been handled! Thanks for everything!

**Pull request merged**
