### PR TITLE
Add tremor to opensource projects

### PR DESCRIPTION
**Pull request by mfelsche**
## Your project

**1Password Teams url**: tremor.1password.com

**Project name**:  Tremor

**Short description**: Tremor is an early stage event processing system for unstructured data with rich support for structural pattern matching, filtering and transformation.

**Project age**: 2 years

**Number of core contributors**: 5

**Project website**: https://tremor.rs

**Repository url**: https://github.com/tremor-rs/tremor-runtime

**Latest release url**: https://github.com/tremor-rs/tremor-runtime/releases/tag/v0.9.0

**License type**: Apache 2.0

**License url**: https://github.com/tremor-rs/tremor-runtime/blob/v0.9.0/LICENSE

## Tell us about yourself

**Name**: Matthias Wahl

**Email**: tremor@m7w3.de

**Project role**: Core Contributor

**Website**: https://github.com/mfelsche

### CODE REVIEW

**Review by darach — APPROVED** [review]
👍

**Comment by Licenser** [comment]
:+1: <3

**Review by Licenser — APPROVED** [review]

**Comment by oliverdunk** [comment]
Thanks for your application, @mfelsche! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under a year's time, as explained in the README. That way, we can look at continuing our support.

**Comment by Licenser** [comment]
<3 from the tremor tream!

**Pull request merged**
