### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jimmyliao**
## Your project

**1Password Teams url**: team-cksh.1password.com (create the account before applying).

**Project name**:   React Native Demo site: chsh https://jimmyliao.medium.com/

**Short description**: Doing good things with childcare / eldercare.

**Project age**: 2 years

**Number of core contributors**: 3

**Project website**:
https://jimmyliao.medium.com/

**Repository url**: https://github.com/jimmyliao/RN_Camera_Demo

**Latest release url**:

**License type**: e.g. MIT, BSD, GPL, etc.
MIT

**License url**: A copy of the license terms and conditions for your software.

## Tell us about yourself

**Name**: Jimmy Liao

**Email**: sjliao@gmail.com

**Project role**:

**Website**: link to GitHub profile page, project page bio, etc.
jimmyliao.github.io

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi @jimmyliao! Thanks for your application. Just to check, do you plan to use 1Password for managing passwords associated with the management of your open source project?

**Comment by jimmyliao** [comment]
> Hi @jimmyliao! Thanks for your application. Just to check, do you plan to use 1Password for managing passwords associated with the management of your open source project?

Yes, I would like to apply within my open source project.

**Comment by jimmyliao** [comment]
> Hi @jimmyliao! Thanks for your application. Just to check, do you plan to use 1Password for managing passwords associated with the management of your open source project?

Already resolve conflict. please check it. Thanks.

**Comment by oliverdunk** [comment]
Thanks for your application, @jimmyliao! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under a year's time, as explained in the README. That way, we can look at continuing our support.

**Pull request merged**
