### PR TITLE
Adding ReactNativeV2ex to the teams list

### PR DESCRIPTION
**Pull request by funnyzak**
#### 1Password Teams URL ####

https://team-ychub.1password.com

#### Project Name ####

React Native V2EX

#### Short Description ####

The project used React Native to build a V2EX mobile client application. The purpose was to build a React Native rapid development scaffold. The client data is based entirely on the V2EX open API.

#### Project Age ####

5 months。

#### Number Of Core Contributors ####

2

#### Repository URL(s) ####

https://github.com/funnyzak/react-native-v2ex

#### Latest Release URL(s) ####

https://github.com/funnyzak/react-native-v2ex/releases

#### License Type ####

MIT

#### License URL ####

https://github.com/funnyzak/react-native-v2ex/blob/dev/LICENSE

## A Bit About Yourself  ##

Full-stack Developer. UTC+08:00.
Open source is something I'm interested in right now.

#### Name ####

Leon

#### Email ####

silenceace@gmail.com.

#### Project Role ####

core developer.

#### Profile/Website ####

https://github.com/funnyzak

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi Leon, I've sent you an email! If you can reply when you're able to and we can try to get this merged :)

**Comment by funnyzak** [comment]
@oliverdunk 

Hi, Oliver.
I deleted **team-ychub** account by mistake earlier. 
Now I created **[ychub](https://ychub.1password.com/)** and now you can help me to set up this team account if you can.

Thank you very much!

**Comment by oliverdunk** [comment]
Thanks for your application, @funnyzak! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

**Comment by funnyzak** [comment]
Thanks @oliverdunk .

**Pull request merged**
