### PR TITLE
Add RVM

### PR DESCRIPTION
**Pull request by pkuczynski**
## RVM

**1Password Teams url**: http://rvm-team.1password.com

**Project name**:  RVM

**Short description**: RVM is a command-line tool which allows you to easily install, manage, and work with multiple ruby environments from interpreters to sets of gems.

**Project age**: since 2009

**Number of core contributors**: 3

**Project website**: http://rvm.io

**Repository url**: https://github.com/rvm/rvm/

**Latest release url**: https://github.com/rvm/rvm/releases/tag/1.29.7

**License type**: Apache License, Version 2.0

**License url**: https://github.com/rvm/rvm/blob/master/LICENSE

## Tell us about yourself

**Name**: Piotr Kuczynski

**Email**: piotr.kuczynski@gmail.com

**Project role**: Core Contributor

**Website**:
https://github.com/pkuczynski 
https://www.linkedin.com/in/piotrkuczynski

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hey @pkuczynski! Thanks for your application. I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to [add additional core contributors](https://support.1password.com/add-remove-team-members/) as you see fit.

Finally, do reach out to us in just under a year's time, as explained in the README. That way, we can look at continuing our support.

**Comment by pkuczynski** [comment]
Thanks! :)

**Comment by pkuczynski** [comment]
Could someone renew our membership please?

**Comment by oliverdunk** [comment]
> Could someone renew our membership please?

Hi! Could you email opensource@1password.com for me? We ask that you do that once a year, so we can check your eligibility.

**Comment by pkuczynski** [comment]
Just did it! Thanks!

**Pull request merged**
