### PR TITLE
Add secureReturn

### PR DESCRIPTION
**Pull request by secureReturn**
## Your project

**1Password Teams url**: securereturn.1password.com (create the account before applying).

**Project name**:  secureReturn

**Short description**: secureReturn is a community of like-minded reverse engineering and security enthusiasts developing open source security tools.

**Project age**: 6+ months

**Number of core contributors**: 2

**Project website**: https://sec-r.et

**Repository url**: https://github.com/iGio90/Dwarf
https://github.com/secRet-re

**Latest release url**: NA

**License type**: GPL

**License url**: https://raw.githubusercontent.com/iGio90/Dwarf/master/LICENSE

## Tell us about yourself

**Name**: Giovanni Rocca

**Email**: secureret@gmail.com

**Project role**: Founder / Owner

**Website**: https://sec-r.et

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi,

Thanks for your application! Would you be able to have someone with activity in the project comment here? That would be a great way to check this application is being made by someone involved with the work :)

As soon as I see that, I'll get the promotion setup for you!

**Comment by secureReturn** [comment]
oh sure thing, sorry about that. @iGio90

**Comment by iGio90** [comment]
Pong :)

**Comment by oliverdunk** [comment]
Thanks for jumping in @iGio90! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under a year's time, as explained in the README. That way, we can look at continuing our support.

**Pull request merged**
