### PR TITLE
WSA-Script Project

### PR DESCRIPTION
**Pull request by YT-Advanced**
#### 1Password Teams URL
team-wsateam.1password.com

#### Project Name
[WSA-Script](http://github.com/YT-Advanced/WSA-Script)

#### Short Description
The small web-app using HTML and Github Action for helping user to integrate Magisk root and Google Apps into Windows Subsystem for Android (WSA), which will be powerful for user who working with Android simulator and for Android app tester

#### Project Age
About 2 years

#### Number Of Core Contributors
4

#### Web-app Website
https://YT-Advanced.github.io/WSA-Script/

#### Repository URL(s)
https://github.com/YT-Advanced/WSA-Script

#### Latest Release URL(s)
https://github.com/YT-Advanced/WSA-Script/releases/latest

#### License
GNU
https://github.com/YT-Advanced/WSA-Script/blob/main/LICENSE

#### Name
Hoàng Gia Bảo

#### Email
giabaodzabb@duck.com

#### Project Role
Owner

#### Profile/Website
https://github.com/YT-Advanced

#### Can we contact you?
We'd love to be in touch to learn how you're using 1Password. Would you be open to our Developer Advocates reaching out?
- [x] Yes, I'm open.

### CODE REVIEW

**Comment by jodyheavener** [comment]
Thanks for your application, @YT-Advanced! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would highly recommend implementing a [recovery plan for your team](https://support.1password.com/team-recovery-plan/) in case access for a particular contributor is ever lost. You are also welcome to add additional core contributors as you see fit.

Also, we'd love to hear more about your experience using 1Password in your development workflows! Feel free to join us over on the [1Password Developers Slack](https://join.slack.com/t/1password-devs/shared_invite/zt-15k6lhima-GRb5Ga~fo7mjS9xPzDaF2A) workspace 🙂

**Comment by YT-Advanced** [comment]
@jodyheavener Sorry for tagging you. Recently, I have lost access to my old computer, which is saving my Emergency Kit. So I don't have access to my Team Account. Can you help me to set one of current member to be the owner of team or revert the promotion in my current team and apply it into the new team.
Thanks and hope you have a nice day !

**Comment by jodyheavener** [comment]
Hi @YT-Advanced - for this kind of support you should reach out to support@1password.com and our team would be happy to help you out.

**Comment by YT-Advanced** [comment]
@jodyheavener Thanks for your reply. Recently, I have contact 1password support team and they said that I must delete my account. So can you add the subscription again to my new team. Thanks

**Pull request merged**
