### PR TITLE
feat: add sycer dev

### PR DESCRIPTION
**Pull request by Fyko**
## Your Project ##
Sycer Development
#### 1Password Teams URL ####

https://sycerdevelopment.1password.com/home

#### Project Name ####
Sycer Development
#### Short Description ####
Sycer Development is a firm specializing in the development of Discord bots.
#### Project Age ####
Born in December 2019
#### Number Of Core Contributors ####
1
#### Project Website ####
https://sycer.dev/
#### Repository URL(s) ####
https://github.com/sycer-dev/giveaways
https://github.com/sycer-dev/giveaways-interactions
https://github.com/sycer-dev/thoth
https://github.com/sycer-dev/dapi
#### License Type ####

MIT or Apache 2.0

#### License URL ####

https://github.com/sycer-dev/giveaways/blob/main/LICENSE
https://github.com/sycer-dev/giveaways-interactions/blob/main/LICENSE

#### Name ####
Carter Himmel
#### Email ####
fyko@sycer.dev
#### Project Role ####
CEO and Founder
#### Profile/Website ####

https://github.com/Fyko
https://fyko.net

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi @Fyko, thanks for your application! Would you be able to share a bit more about Sycer and confirm that your 1Password account will be used for your open source projects, not any business activities of Sycer? I notice some paid plans noticed on your Twitter which may affect your eligibility here.

**Comment by Fyko** [comment]
While we have a variety of open source products and services, we do have paid ones. I planned on using 1Password to store passwords for our company accounts (Github, Twitter, Gmail, etc.) and our SSH keys. Have I missed the memo?

**Comment by oliverdunk** [comment]
> While we have a variety of open source products and services, we do have paid ones. I planned on using 1Password to store passwords for our company accounts (Github, Twitter, Gmail, etc.) and our SSH keys. Have I missed the memo?

Our general rule is that 1Password needs to be used exclusively for the open source project. From the README:

> If you or your company work on commercial projects, consider 1Password Business. For example, AgileBits has several open source projects, but wouldn't qualify for a free team account because it's a business.

Do you agree that the open source program might not be the right fit?

**Comment by oliverdunk** [comment]
Hey @Fyko! I'm going to close this one for now. Let me know if you have any thoughts though - more than happy to re-open and take another look if that ends up making sense.

**Pull request closed without merging**
