### PR TITLE
Added an entry 

### PR DESCRIPTION
**Pull request by kkoumantaros**
## Your project

**1Password Teams url**: argo-team.1password.com

**Project name**:  Argo Service Level Monitoring & Messaging Framework
**Short description**: ARGO is a lightweight service for Service Level Monitoring designed for medium and large sized Research Infrastructures

**Project age**:  >6 Years

**Number of core contributors**: 10

**Project website**: http://argoeu.github.io/overview/ 

**Repository url**: https://github.com/orgs/ARGOeu/dashboard 

**Latest release url**: https://github.com/orgs/ARGOeu/dashboard

**License type**:  Apache .

**License url**: https://argo.egi.eu/egi/termsofUse

## Tell us about yourself

**Name**:  Kostas Koumantaros

**Email**: kkoum@admin.grnet.gr 

**Project role**: Stakeholder

**Website**: https://github.com/kkoumantaros

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi @kkoumantaros! Sorry for keeping you waiting so long.

Do you have an open source licence for any of your repositories? I tried to find one, but didn't see anything.

Also, are you able to update your MR for me, so your project is added at the bottom? We try to keep things chronological :)

**Comment by oliverdunk** [comment]
Hi @kkoumantaros, are you still interested in the promotion?

**Comment by kkoumantaros** [comment]
Yes we are but due to the fact we are working from home the last couple of weeks our response to this was delayed

**Comment by oliverdunk** [comment]
Hi @kkoumantaros! Just sending another bump here. If you'd rather, I can close this and you can re-open it when you're ready.

**Comment by oliverdunk** [comment]
Closing this for now, please let me know if you'd like it reopening.

**Pull request closed without merging**
