### PR TITLE
added fervid

### PR DESCRIPTION
**Pull request by prolixalias**
#### 1Password Teams URL ####
https://fervid.1password.com/

#### Project Name ####
secure_linux_cis

#### Short Description ####
Implement Linux controls defined in the Center for Internet Security (CIS) benchmarks

#### Project Age ####
2 years

#### Number Of Core Contributors ####
3

#### Project Website ####
https://forge.puppet.com/modules/fervid/secure_linux_cis

#### Repository URL(s) ####
https://github.com/fervidus/secure_linux_cis

#### Latest Release URL(s) ####
https://github.com/fervidus/secure_linux_cis/releases/tag/v2.1.17

#### License Type ####
Apache 2.0

#### License URL ####
https://github.com/fervidus/secure_linux_cis/blob/main/LICENSE

#### Name ####
Paul Talbot

#### Email ####
paul@fervid.us

#### Project Role ####
Author/Maintainer

#### Profile/Website ####
https://github.com/prolixalias

#### Comments ####
New to 1p, it came highly recommended by partners at Puppet

### CODE REVIEW

**Comment by prolixalias** [comment]
For what it's worth, Fervid has a few open source projects in-flight that would benefit from your solution. I'd run into a minefield of "gotchas" and initially gone down the wrong road exploring hashicorp's offering... That's when a partner org suggested 1p enthusiastically. Thank you for consideration in the promotion. Lastly, is it possible to participate in any beta programs for non-rosetta M1/arm64? We'd be happy to help.

**Comment by oliverdunk** [comment]
Hey @prolixalias!

Great to hear that you came from Puppet! It's always nice to hear that sort of thing.

Before I accept this, would you be able to say a little bit about Fervid as a company and how that links to usage of 1Password? One thing we usually don't support is for-profit companies wanting to use 1Password because they happen to have a few open source projects.

> Lastly, is it possible to participate in any beta programs for non-rosetta M1/arm64? We'd be happy to help.

I'm not super in the loop here, so if you want to send an email, I can definitely remind myself what state each of the apps are in. I can say for definite that there aren't any private betas you're missing out on though!

**Comment by prolixalias** [comment]
Hi @oliverdunk, thank you for responding so quickly. Sure thing! We're a virtualization+automation company specializing in large scale open source deployment. Our largest partner is Puppet, we fill a PS role for them. The only thing we sell is our time to design and implement. My current engagement is moving an international airline from "vendored" Puppet Enterprise to an amalgam of OSP and other open source tools to mimic accordingly. A meeting last week ended with their CTO commenting, "Successful Q4 migration from PE to OSP was the most significant event of 2021."

The first item I'm planning to use 1Password's cli with is CIS recommendations for bootloader password. It's a perfect fit and most smaller orgs can't support Hashcorp Vault, which was the beginning of this journey.

There are a two other WIP open source projects we're assuming would benefit - one that needs a similar solution for storing keys in an OSP+r10k interaction. Lastly, we have an open source (but not visible at the moment) `letsencrypt plugin integrations` project that needs token storage for Azure, GCP and credentials for AWS. If you'd like to see that WIP, I'm happy to add you as a collaborator temporarily.

**Comment by oliverdunk** [comment]
Thanks for the extra context! I've gone ahead and applied the promotion to your account. The one thing I do want to reiterate is that the account should be used specifically for these open source projects - if you want to significantly grow the number of users on your account and use it for your business as a whole, please reach out so we can discuss the best path forward :)

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

**Pull request merged**
