### PR TITLE
Adding Digital Excellence to README

### PR DESCRIPTION
**Pull request by Brend-Smits**
## Your project

**1Password Teams url**: https://digitalexcellence.1password.com

**Project name**:  Digital Excellence

**Short description**:  A lot of employees and students of Schools and Universities create a lot of nice products. As a hobby, for their work or because of a school project. These can be software solutions, small scripts, research papers, thesis but possibly also project ideas and proposals for others to pick up. Unfortunately, most of them remain private and are not known by the majority of the population. The goal of the Digital Excellence-platform (short: DeX) is to make all this work more findable and thus improving collaboration.
Long description can be found[ here.](https://github.com/DigitalExcellence/dex-backend/wiki/General-Description)

**Project age**: 15 weeks

**Number of core contributors**: 12 core contributors

**Project website**: https://dex.software

**Repository url**: Backend: https://github.com/DigitalExcellence/dex-backend 
  Frontend: https://github.com/DigitalExcellence/dex-frontend

**Latest release url**: https://dex.software

**License type**: GNU Lesser General Public License v3.0

**License url**: https://github.com/DigitalExcellence/dex-backend/blob/develop/LICENSE.md

## Tell us about yourself

**Name**: Brend Smits

**Email**: brend_smits@hotmail.com

**Project role**: Project leader & Core developer

**Website**: https://github.com/brend-smits

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi,

It looks like there are some conflicts here, and I don't have write permission to fix them. Could you take a look for me?

**Comment by Brend-Smits** [comment]
Hi @oliverdunk ,

Thanks for following up, it should be resolved now!

**Comment by oliverdunk** [comment]
Thanks! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under a year's time, as explained in the README. That way, we can look at continuing our support.

**Comment by Brend-Smits** [comment]
Sweet, thanks a lot. 
We'll be in touch for sure.

**Pull request merged**
