### PR TITLE
Add Auroville

### PR DESCRIPTION
**Pull request by shankardevy**
## Your project

**1Password Teams url**: auroville.1password.com (create the account before applying).

**Project name**:  Auroville Campus

**Short description**: 

**Project age**: Auroville community itself is 53 years old and had been doing a lot of educational activities offline for all these years. It's a non profit organisation in India. Now we are moving to online education as well with this platform and this one is more than 1 year old.

**Number of core contributors**:  20 (some of them are non devs who don't commit code but still very much part of the work that we do)

**Project website**: https://edu.auroville.org and https://auroville.org

**Repository url**:  https://github.com/Auroville/campus

**Latest release url**: 

**License type**: MIT

**License url**: https://github.com/Auroville/campus/blob/master/LICENSE

## Tell us about yourself

**Name**:  Shankar Dhanasekaran

**Email**: shankardevy@auroville.org.in

**Project role**: CTO

**Website**: link to GitHub profile page, project page bio, etc. https://github.com/shankardevy 
Author of a few books on Elixir/Phoenix. Have open sourced my book on Phoenix framework : https://shankardevy.com/phoenix-inside-out-mpf/

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi @shankardevy, what a wonderful project! Just to confirm, is this for the maintenance of your open source projects or your non profit as a whole? We'd be happy to provide an account for core contributors but for the larger non profit it would be best to chat over email :)

**Comment by shankardevy** [comment]
hi @oliverdunk thanks for your quick response. Though it would be great to have the account created for the whole organization, right now, I'm applying only for the core group that is managing the codebase and involved in testing the code, organising the educational events on ground. Thank you for your time in reviewing this.

**Comment by oliverdunk** [comment]
Got it! Thanks for clarifying @shankardevy. I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under two year's time, as explained in the README. That way, we can look at continuing our support.

**Comment by shankardevy** [comment]
Thanks a lot!

**Pull request merged**
