### PR TITLE
Add 1build to Open Source Project list

### PR DESCRIPTION
**Pull request by gopinath-langote**
## 1build

**1Password Teams url**: 1build.1password.com

**Project name**:  1build

**Short description**: Frictionless way of managing project-specific commands

**Project age**:  4 months

**Number of core contributors**: 6

**Project website**: https://github.com/gopinath-langote/1build

**Repository url**: https://github.com/gopinath-langote/1build

**Latest release url**: https://pypi.org/project/1build/1.1.1/

**License type**: MIT

**License url**: https://github.com/gopinath-langote/1build/blob/master/LICENSE

## Tell us about yourself

**Name**: Gopinath Langote

**Email**: gopinathlangote11@gmail.com

**Project role**: Maintainer and Contributor

**Website**: https://github.com/gopinath-langote/

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi @gopinath-langote,

Thanks for your application. It looks like you might have added an '!' to your project's name in the README accidentally?

Will hold off merging until I'm sure everything's right :)

**Comment by gopinath-langote** [comment]
@oliverdunk 

Yes `!` was by mistake :( 

I have updated the PR


Best,
Gopinath

**Comment by oliverdunk** [comment]
Hi @gopinath-langote, it looks like you forgot to add the '1' when you removed the '!'. I went ahead and fixed that, and applied the promotion to your account :)

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under a year's time, as explained in the README. That way, we can look at continuing our support.

**Comment by gopinath-langote** [comment]
@oliverdunk 
Thanks for approval.

**Pull request merged**
