### PR TITLE
Propose BrightChain for OpenSource

### PR DESCRIPTION
**Pull request by JessicaMulein**
#### Project Name ####
BrightChain: The Revolution(ary) Network

#### Short Description ####
A Lightweight BlockChain- LightChain based on a Brightnet Blockstore- BrightChain. All the benefits of blockchain dApps and contracts without the mining and waste. Unlimited storage for everyone, and a mathematically reinforced and moderated community that will last for the ages. 

#### Project Age ####
Most recent iteration of public code is just a few months old

#### Number Of Core Contributors ####
1 at the moment, 2 juniors ramping up, one senior pending confirmation from legal

#### Project Website ####
https://apidocs.therevolution.network

#### Repository URL(s) ####
https://github.com/The-Revolution-Network/BrightChain

#### Latest Release URL(s) ####
all releases alpha-not yet useful, listed in github and docker hub

https://hub.docker.com/layers/brightchain/core/1020438154/images/sha256-50789aabf94b01751e5270ddfb2d1f7e81752c4094572046260881707561776c?context=explore

auto-deploys to docker hub although the containers are not yet useful

#### License Type ####

Apache 2.0

#### License URL ####

https://github.com/The-Revolution-Network/BrightChain/blob/main/LICENSE.md

## A Bit About Yourself  ##
Software engineer at microsoft

#### Name ####
Jessica Mulein

#### Email ####
jessica@mulein.com

#### Project Role ####
principal engineer

#### Profile/Website ####

https://github.com/JessicaMulein

#### Comments ####
Love 1password. Just discovered your open source aspect while looking for your source code, and thought maybe will do secret management with 1password assist.

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi @JessicaMulein - thanks for your PR! Have you signed up for a 1Password Teams account yet? There are some instructions for that in the README :)

**Comment by JessicaMulein** [comment]
I did!

**Comment by oliverdunk** [comment]
> I did!

Nice! Could you share the team URL for me? You should be able to find that in the settings of your account, or on your Emergency Kit.

**Comment by JessicaMulein** [comment]
Should be brightchain.1password.com

**Comment by oliverdunk** [comment]
Thanks @JessicaMulein - got it! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under two year's time, as explained in the README. That way, we can look at continuing our support.

**Comment by JessicaMulein** [comment]
Thank you :)

**Pull request merged**
