### PR TITLE
Add Open Source Observer

### PR DESCRIPTION
**Pull request by ryscheng**
Adding opensource.observer

#### 1Password Teams URL
https://karibalabs.1password.com/

#### Project Name
Kariba Labs

#### Project Age
2 months

#### Number Of Core Contributors
3

#### Project Website
https://www.opensource.observer

#### Repository URL(s)
https://github.com/opensource-observer/oso

#### Latest Release URL(s)
Open Source Observer is continuously deployed via Vercel and GitHub actions
https://github.com/opensource-observer/oso/pulls?q=is%3Apr+is%3Aclosed
https://github.com/opensource-observer/oso/actions

#### License
Apache 2.0
https://github.com/opensource-observer/oso/blob/main/LICENSE

#### Name
Raymond Cheng

#### Email
ray@karibalabs.co

#### Project Role
Tech lead

#### Profile/Website
- https://github.com/ryscheng
- https://www.linkedin.com/in/ryscheng/
- https://www.raymondcheng.net/

#### Anything else to add?
Kariba Labs is the name of the team that is maintaining open source observer

#### Can we contact you?
We'd love to be in touch to learn how you're using 1Password. Would you be open to our Developer Advocates reaching out?

- [x] Yes, I'm open.

### CODE REVIEW

**Comment by jodyheavener** [comment]
Hi @ryscheng, thanks for your application! It looks like you haven't included a URL for the 1Password account you'd like to apply with. If you can let me know I will happily continue with your application. Thanks!

**Comment by ryscheng** [comment]
@jodyheavener I'm sorry about that! here it is
https://karibalabs.1password.com/

**Comment by jodyheavener** [comment]
Thanks for this information, @ryscheng! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would highly recommend implementing a [recovery plan for your team](https://support.1password.com/team-recovery-plan/) in case access for a particular contributor is ever lost. You are also welcome to add additional core contributors as you see fit.

Also, we'd love to hear more about your experience using 1Password in your development workflows! Feel free to join us over on the [1Password Developers Slack](https://join.slack.com/t/1password-devs/shared_invite/zt-15k6lhima-GRb5Ga~fo7mjS9xPzDaF2A) workspace 🙂

**Comment by ryscheng** [comment]
Thank you! I'll join the Slack now :-)

**Pull request merged**
