### PR TITLE
Add AEGEE's OMS (team name: MyAEGEE)

### PR DESCRIPTION
**Pull request by linuxbandit**
## Your project

**1Password Teams url**: myaegee.1password.com (create the account before applying).

**Project name**:  OMS (Online Membership System)

**Short description**: [OMS](https://oms-project.atlassian.net) is an open-source project born from the youth NGO AEGEE-Europe. It aims to provide an intranet which other YNGOs (and more) can use to manage their members and internal events, and it allows customisation through pluggable modules.

**Project age**: Since 2014

**Number of core contributors**: 3

**Project website**: https://oms-project.atlassian.net

**Repository url**: https://github.com/AEGEE/oms-docker

**Latest release url**: The URL is not available, we're not yet that pro :( but we're building the devops pipeline

**License type**: Apache2

**License url**: https://github.com/AEGEE/oms-docker/blob/master/LICENSE.txt

## Tell us about yourself

**Name**: Fabrizio

**Email**: fabrizio@aegee.eu

**Project role**: I started the project when I joined the NGO; I am the main architect and devops

**Website**: github.com/linuxbandit

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hey @linuxbandit! Thanks for your application. I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to [add additional core contributors](https://support.1password.com/add-remove-team-members/) as you see fit.

Finally, do reach out to us in just under a year's time, as explained in the README. That way, we can look at continuing our support.

**Comment by linuxbandit** [comment]
Thanks @oliverdunk ! At the time when you merged the request, my other fellow @serge1peshcoff (the second of the three core contributors) didn't accept yet the invitation, he's now owner so that should be it!

A question about the 'plan', in the preferences I see that we are in trial mode - I get it that instead of 30-days trial we have the year you just mentioned? And in one year we shall just reach out to you?

Thank you for the opportunity and for the great product! We would like to add your logo to our "patrons/donors" (don't know the correct English word) page on the website, who can we ask permission to?

Take care,
Fabrizio

**Comment by oliverdunk** [comment]
Hi Fabrizio, no problem.

I'm not sure I understood what you were saying about the new owner. Am I right in thinking that there's nothing we need to do on our end?

With regards to the plan, you've got it. We use the trial mechanism to provide your free accounts, and you should find some information in the `README` of this repository about how to renew in a year's time.

Finally, offering to mention our name is very generous of you. Do you have a link to where we'd appear? It's likely fine, as long as it's clear we're not associated.

**Comment by linuxbandit** [comment]
Yes, I was referring to your advice of not being locked out of the organisation, but I noticed later that you wrote "If you haven't done so already". So that should be it :)

About the "thank you" page, we are constructing it, and we will take notice to include that we are not affiliated in any way - thanks for the advice! Would you like us to notify you when we publish it?

**Comment by oliverdunk** [comment]
Sorry for my delayed response here. Please do send a link when you’ve made the page, I’d love to see it!

**Comment by serge1peshcoff** [comment]
@oliverdunk check this out: https://my.aegee.eu/about

**Comment by oliverdunk** [comment]
That's brilliant, thanks @serge1peshcoff! Hope 1Password is working well for you.

**Comment by serge1peshcoff** [comment]
@oliverdunk we are already actively using it, and it's great! Thanks for everything.

**Pull request merged**
