### PR TITLE
add alfred-workflows

### PR DESCRIPTION
**Pull request by alanhg**
#### 1Password Teams URL ####

https://alfredworkflows.1password.com/

#### Project Name ####
Alfred Workflows

#### Short Description ####

Labor duplication is physical work, so need to use tools to do automated treatment, saving lives.

#### Project Age ####

2.5years+

#### Number Of Core Contributors ####

1

#### Project Website ####

https://github.com/alanhg/alfred-workflows

#### Repository URL(s) ####

https://github.com/alanhg/alfred-workflows

#### Latest Release URL(s) ####

https://github.com/alanhg/alfred-workflows/releases/tag/v1.0

#### License Type ####
MIT
#### License URL ####

https://github.com/alanhg/alfred-workflows/blob/master/LICENSE

#### Name ####
Alan He

#### Email ####

alan@1991421.cn

#### Project Role ####

Owner & Contributor

#### Profile/Website ####

https://1991421.cn

## Comments ####

I love 1Password. It make me better and productive.

### CODE REVIEW

**Comment by oliverdunk** [comment]
Thanks for your application, @alanhg! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.

Finally, do reach out to us in just under two year's time, as explained in the README. That way, we can look at continuing our support.

**Comment by alanhg** [comment]
> Thanks for your application, @alanhg! I've gone ahead and applied the promotion to your account.
> 
> If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.
> 
> Finally, do reach out to us in just under two year's time, as explained in the README. That way, we can look at continuing our support.

Thank you!

**Comment by alanhg** [comment]
> Thanks for your application, @alanhg! I've gone ahead and applied the promotion to your account.
> 
> If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.
> 
> Finally, do reach out to us in just under two year's time, as explained in the README. That way, we can look at continuing our support.

> Thanks for your application, @alanhg! I've gone ahead and applied the promotion to your account.
> 
> If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to add additional core contributors as you see fit.
> 
> Finally, do reach out to us in just under two year's time, as explained in the README. That way, we can look at continuing our support.

My 1Password subscription is about to expire. Could you please help me switch to a perpetual license?

**Comment by jodyheavener** [comment]
@alanhg This should be resolved now. Thanks for reaching out.

**Comment by alanhg** [comment]
> @alanhg This should be resolved now. Thanks for reaching out.

thanks

**Pull request merged**
