### PR TITLE
Add Home Assistant

### PR DESCRIPTION
**Pull request by robbiet480**
## Your project

**1Password Teams url**: homeassistant.1password.com

**Project name**: Home Assistant

**Short description**: Open source home automation that puts local control and privacy first. Powered by a worldwide community of tinkerers and DIY enthusiasts. Perfect to run on a Raspberry Pi or a local server.

**Project age**: 5 years, 6 months, 16 days ([first commit was Tuesday, September 17, 2013](https://github.com/home-assistant/home-assistant/commit/d55e4d53cccc9123d03f45c53441e7cbfc58e515))

**Number of core contributors**: 10 core, 3092 total across all repos (of those, only maybe 5 would need 1P accounts)

**Project website**: https://www.home-assistant.io

**Repository url**: https://github.com/home-assistant/home-assistant

**Latest release url**: https://www.home-assistant.io/blog/2019/03/20/release-90/

**License type**: [All code is Apache 2.0, documentation is Creative Commons](https://www.home-assistant.io/blog/2017/01/21/home-assistant-governance/#licensing)

**License url**: https://www.home-assistant.io/developers/license/ (see above link for more info)

## Tell us about yourself

**Name**: Robbie Trencheny

**Email**: me@robbiet.us

**Project role**: Chief Infrastructure Engineer, mobile apps developer, community co-manager

**Website**: [GitHub](https://github.com/robbiet480), [Twitter](https://twitter.com/robbie)

PS: **Love** 1Password, I use it personally, rolled it out at my company of 40 people and am excited to bring it to Home Assistant!

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hey @robbiet480! Thanks for your application, and the kind words about 1Password. I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to [add additional core contributors](https://support.1password.com/add-remove-team-members/) as you see fit.

Finally, do reach out to us in just under a year's time, as explained in the README. That way, we can look at continuing our support.

**Comment by robbiet480** [comment]
@oliverdunk Thanks so much, already got everyone added and briefed on emergency kit. Also set a reminder for just under a year. Thanks!

**Comment by oliverdunk** [comment]
Perfect @robbiet480! While Recovery can sometimes save you, it's definitely good practice to have everyone making their own plan for emergencies.

Have a brilliant rest of your day.

**Comment by robbiet480** [comment]
@oliverdunk Just sent an email seeking renewal to the address specified in the README. Thought i'd bump this PR and make you aware just in case. Thanks!

**Pull request merged**
