### PR TITLE
Natlv patch 1

### PR DESCRIPTION
**Pull request by natlv**
#### 1Password Teams URL
nathanlooenping@gmail.com

#### Project Name
HawkerRate

#### Short Description
A solution for both buyers of hawker centre food to read, create, and post ratings and reviews for individual stalls, while increasing visibility for hawker stall owners.

#### Project Age
31 days

#### Number Of Core Contributors
4

#### Project Website
https://hawkerrate.my.canva.site/

#### Repository URL(s)
https://replit.com/@natlv/the-boys#hawkerrate/

## A Bit About Yourself
Incoming University Year 1 Undergraduate in Computer Science

#### Name
Nathan Loo Enping

#### Email
nathanlooenping@gmail.com

#### Project Role
Project Lead

#### Profile/Website
https://github.com/natlv

#### Can we contact you?
We'd love to be in touch to learn how you're using 1Password. Would you be open to our Developer Advocates reaching out?

- [ ✓] Yes, I'm open.

### CODE REVIEW

**Comment by jodyheavener** [comment]
Hi @natlv - this PR is still in Draft. Are you intending it for it to be reviewed yet?

**Comment by natlv** [comment]
Hi Jody,

Yes please, thank you.

Nathan

**Comment by jodyheavener** [comment]
@natlv This PR is marked as Draft - please mark as Ready for Review

**Comment by jodyheavener** [comment]
Hi @natlv - I am just checking in again. If you would like this application reviewed please mark it as "Ready for Review". This PR will be closed shortly from inactivity otherwise. If you have any questions about this process please let me know. Thank you for understanding.

**Pull request closed without merging**
