### PR TITLE
todo

### PR DESCRIPTION
**Pull request by realJoshLee**
## Your project

**1Password Teams url**: team-joshleepw.1password.com

**Project name**:  
TODO

**Short description**:
An open source project to manage all of your tasks for personal or company use. This is hosted under a portfolio url becasue it is a project with the creator and some friends. We made this project because we could never find a todo list that has everything that we were looking for, so we decided that we would make our own with everything that we wanted.

**Project age**: 
3 months. Just published to GitHub after refining.

**Number of core contributors**:
4

**Project website**:
https://joshlee.pw/webapps/todo/

**Repository url**:
https://github.com/realJoshLee/TODO-OPENSOURCE

**Latest release url**:
https://joshlee.pw/webapps/todo/release/latest.zip

**License type**: e.g. MIT, BSD, GPL, etc.
MIT

**License url**: A copy of the license terms and conditions for your software.
https://joshlee.pw/webapps/todo/toc.html
https://joshlee.pw/webapps/todo/LICENSE

## Tell us about yourself

**Name**: 
Josh Lee

**Email**:
josh@joshlee.pw

**Project role**:
Creator

**Website**: link to GitHub profile page, project page bio, etc.
GitHub: https://github.com/realJoshLee/
Project Page: https://github.com/realJoshLee/TODO-OPENSOURCE
Portfolio: https://joshlee.pw/
Note: This is a project under this url becasue I plan on hosting & creating other open source projects.

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi @realJoshLee! It looks like you've updated one of our templates. To apply, you just need to update the README file, to add your project at the bottom.

Could you go ahead and do that?

It also looks like your repository is empty at the moment. It would make sense to have some code there before opening your application.

**Comment by realJoshLee** [comment]
@oliverdunk Added the files to the GitHub repo. Additionally, added my edit for adding my open source project to the bottom of the `README.md` file. Thank you for the response!

**Comment by oliverdunk** [comment]
@realJoshLee, the repo looks great! I'm not seeing your README changes, though. Do they still need pushing?

Don't forget to remove the changes to the template file!

**Comment by oliverdunk** [comment]
Ah, it's a new MR. Closing this one.

**Comment by realJoshLee** [comment]
So just to confirm Oliver, is this eligible for me to email in for renewal every year?

**Comment by oliverdunk** [comment]
> So just to confirm Oliver, is this eligible for me to email in for renewal every year?

Absolutely. As long as your project remains eligible, you can email in each year, and we'll add an extra 12 months of the promotion.

**Pull request closed without merging**
