### PR TITLE
LibertyLand

### PR DESCRIPTION
**Pull request by Artuto**
## LibertyLand

**1Password Teams url**: libertyland.1password.com

**Project name**:  LibertyLand

**Short description**: Open Source stuff of the LibertyLand Minecraft Server

**Project age**: 2 years~

**Number of core contributors**: 2

**Project website**: libertyland.xyz

**Repository url**: https://github.com/LibertyLand/LLCore

**Latest release url**: Available in our jenkins: https://jenkins.artuto.tk

**License type**: GPL3.

**License url**: https://github.com/LibertyLand/LLCore/blob/master/LICENSE

## Tell us about yourself

**Name**: Arturo Andrade

**Email**: artutogamer@gmail.com

**Project role**: Lead Dev/Owner

**Website**: https://github.com/Artuto

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hi Arturo,

Thank you for your application. It seems that your server would fall under the category of a commercial project, and unfortunately, that means it's not quite what we're looking for here.

I wish you the best of luck with the server, and invite you to reach out to business@1password.com to discuss how 1Password could work for you. Please do also let me know if you think I've made a mistake, providing any additional information that might help.

**Comment by Artuto** [comment]
Well, yes I consider this is an error because players can donate to support
us, however thats completely optional and all the stuff you can get by
paying is obtainable in-game.

**Comment by Artuto** [comment]
Bump?

**Comment by oliverdunk** [comment]
Hi @Artuto,

Please accept my apologies for not getting back to you sooner. In this case, I've decided to accept your application and have applied the promotion to your account. After taking a closer look following your reply, I was convinced that you don't have a commercial objective.

If you haven't done so already, I would definitely recommend implementing a recovery plan for your team in case access for a particular contributor is ever lost: https://support.1password.com/team-recovery-plan/. You are also welcome to [add additional core contributors](https://support.1password.com/add-remove-team-members/) as you see fit.

Finally, do reach out to us in just under a year's time, as explained in the README. That way, we can look at continuing our support.

**Pull request merged**
