### PR TITLE
Show Current Width WordPress plugin

### PR DESCRIPTION
**Pull request by web83info**
Add Show Current Width

#### 1Password Teams URL
web83info.1password.com

#### Project Name
Web83

#### Short Description
Web83 is a software development team focused on WordPress development.

#### Project Age
Our first open source WordPress plugin is open to public on July 6, 2023. (33 days ago)

#### Number Of Core Contributors
1

#### Project Website
https://github.com/web83info

#### Repository URL(s)
https://github.com/web83info/show-current-width

#### Latest Release URL(s)
https://github.com/web83info/show-current-width/releases/tag/v1.1.1

#### License
GPLv2 or later
https://github.com/web83info/show-current-width/blob/main/readme.txt

## A Bit About Yourself
We have been working on WordPress developement for over 10 years.

#### Name
Hirayama, Tomoharu (Web83info)

#### Email
me@web83.info

#### Project Role
Developer

#### Profile/Website
https://github.com/web83info

#### Can we contact you?
We'd love to be in touch to learn how you're using 1Password. Would you be open to our Developer Advocates reaching out?

- [x] Yes, I'm open.

### CODE REVIEW

**Comment by jodyheavener** [comment]
Hi @web83info, thanks for your application! I see you've indicated your project is under GPLv2 license, but I was not able to find a copy of the license itself. Would you be able to put a LICENSE file in your project so others can see?

**Comment by web83info** [comment]
Hi, @jodyheavener. I added LICENSE to my project in version 1.1.2.
Thank you for your work.

https://github.com/web83info/show-current-width/blob/main/LICENSE
https://github.com/web83info/show-current-width/releases/tag/1.1.2

**Comment by jodyheavener** [comment]
Thanks for updating this, @web83info! I've gone ahead and applied the promotion to your account.

If you haven't done so already, I would highly recommend implementing a [recovery plan for your team](https://support.1password.com/team-recovery-plan/) in case access for a particular contributor is ever lost. You are also welcome to add additional core contributors as you see fit.

Also, we'd love to hear more about your experience using 1Password in your development workflows! Feel free to join us over on the [1Password Developers Slack](https://join.slack.com/t/1password-devs/shared_invite/zt-15k6lhima-GRb5Ga~fo7mjS9xPzDaF2A) workspace 🙂

**Comment by web83info** [comment]
Thank you very much for your approval.

**Pull request merged**
